### ISSUE TITLE
Cannot init

### ISSUE THREAD

**Issue by bndw** [bubenshchykov/hc-cli#1]
I've tried freshly created Admin and Notification tokens, but the init function fails with the following error:

```
{ error: 
   { error: 
      { code: 401,
        message: 'Invalid OAuth session',
        type: 'Unauthorized' } } }
```

**Comment by bubenshchykov** [comment]
sorry for a late reply, I missed your issue. I've tested it again, all good, hipchat was changing an API though. How do you create your tokens?

![screen shot 2014-11-25 at 2 57 31 am](https://cloud.githubusercontent.com/assets/1152020/5177355/5aa7e6c2-744f-11e4-8ca8-fc2d59c67e5c.png)
(no worries, i regenerated the token))

``````
alex$ hip init GxuPOU0gPzOAGNt2N3raZmHdVfp4fAKUtaiiOLF3
good!
alex$ hip chat Kon-tiki
joining the room..
Baunbæk > @jnm That's why I asked :) If it crashes that's fine, but if we have to do something different it'd be great to know
Alex Bub > eeeee.... i don't want to crash our instances ) ```
``````

**Comment by bubenshchykov** [comment]
closing as inactive

**Comment by bendellarocco** [comment]
Hello, I am having the same issue.  Both token for api 1 and 2 are failing
